canal:
  server:
    url: 47.97.159.238  #单机配置,local/dev/test环境使用
    port: 9092  #单机配置,local/dev/test环境使用
    destination: example #环境共用参数
    username:
    password:
    subscribe: #需要监控库的mysql表
#      bc_address_library,bc_contact,bc_contact_company,bc_customer,
#      bill_entrust,bill_transport,
#      consigner_info,fleet_info,
#      fleet_vehicle_info,vehicle_info_temp,fleet_vehicle_mapping,
#      bc_goods,queue_appoint_query,queue_appoint_record_log,
#      queue_appoint_trucker,queue_appoint_vehicle,queue_warehouse_notice,
#      queue_warehouse_notice_trucker_mapping,queue_warehouse_notice_vehicle_mapping
      cms_articles
    refreshSeconds: 10 #单位：秒
    zkServers: 47.97.159.238:2181 # zookeeper HA高可用配置,forecast/prod环境使用
    dbname: kuaiche #数据库名称
